### ISSUE TITLE
Pi2 image

### ISSUE THREAD

**Issue by tikismoke** [domogik/domogik#165]
I nearly finished it.
Should we add all plugin in it or only stable one?
For the moment it has only domogik 0.4.2 stable plugins mq as master and domoweb.

Need to find a way to make it smaller. Even if it takes only 1.6go the IMG still make the SD size (8Gigs).

Also what log level should I put: error was my thought. What about it?
Goal is to reduce SD r/w so even no logging at all why not?

Also I think we should reduce other logs from Debian itself. But what to keep or remove?

**Comment by fritz-smh** [comment]
Some points : 

- logs in debug
- about plugins, I would say only the one without hardware/registration : diskfree, weather, brain_base for example
- make sure the password is not yours ;)
- update domogik.cfg and domogik-mq.cfg files to use * instead of interface or ip (check with me on irc for more details)

Fritz

**Comment by fritz-smh** [comment]
Tiki, do we keep this ticket ?

**Comment by tikismoke** [comment]
As a ticket no i don't think.
I broke the SD card before finishing it and no time before Christmas.

**Comment by fritz-smh** [comment]
ok, no issue ;)

I close the ticket. Thanks for all the efforts !
